---
- name: download Zookeeper
  get_url: url=http://mirrors.sonic.net/apache/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz dest=/root/zookeeper-3.4.6.tar.gz

- name: unpack Zookeeper
  command: bash -c "cd /opt && tar xzf /root/zookeeper-3.4.6.tar.gz" creates=/opt/zookeeper-3.4.6

- name: create {{ zookeeper_distr_prefix }}
  shell: cp -r /opt/zookeeper-3.4.6 {{ zookeeper_distr_prefix }} creates={{ zookeeper_distr_prefix }}

- name: add Zookeeper user
  user: name={{ zookeeper_user }} shell=/usr/sbin/nologin state=present

- name: make {{ zookeeper_var_prefix }}
  file: path={{ zookeeper_var_prefix }} state=directory owner={{ zookeeper_user }} group={{ zookeeper_user }} mode=0700
  when: ansible_os_family != 'Elbrus'

- name: make {{ zookeeper_var_prefix }}
  file: path={{ zookeeper_var_prefix }} state=directory owner={{ zookeeper_user }} group={{ zookeeper_user }}
  when: ansible_os_family == 'Elbrus'

- name: make {{ zookeeper_distr_prefix }}/conf
  file: path={{ zookeeper_distr_prefix }}/conf state=directory owner=root group=root mode=0755

- name: put {{ zookeeper_distr_prefix }}/conf/zoo.cfg
  template: src=zookeeper/zoo.cfg dest={{ zookeeper_distr_prefix }}/conf/zoo.cfg owner=root group=root mode=0644 backup=yes

- name: put {{ zookeeper_distr_prefix }}/conf/zookeeper-env.sh
  template: src=zookeeper/zookeeper-env.sh dest={{ zookeeper_distr_prefix }}/conf/zookeeper-env.sh owner=root group=root mode=0644 backup=yes

- name: put {{ zookeeper_distr_prefix }}/bin/{{ zookeeper_start }}
  template: src=zookeeper_start.sh dest={{ zookeeper_distr_prefix }}/bin/{{ zookeeper_start }}
  when: ansible_os_family == 'Elbrus'

- name: put {{ zookeeper_distr_prefix }}/bin/{{ zookeeper_start }}
  shell: chmod 0755 {{ zookeeper_distr_prefix }}/bin/{{ zookeeper_start }}
  when: ansible_os_family == 'Elbrus'

- name: make {{ zookeeper_log_prefix }}
  file: path={{ zookeeper_log_prefix }} state=directory owner={{ zookeeper_user }} group={{ zookeeper_user }} mode=0700
  when: ansible_os_family != 'Elbrus'

- name: make {{ zookeeper_log_prefix }}
  file: path={{ zookeeper_log_prefix }} state=directory owner={{ zookeeper_user }} group={{ zookeeper_user }}
  when: ansible_os_family == 'Elbrus'

- name: put {{ zookeeper_var_prefix }}/myid
  template: src=zookeeper/myid dest={{ zookeeper_var_prefix }}/myid owner=root group=root mode=0644 backup=yes

- name: put zookeeper.rb eye config file
  template: src=zookeeper/eye.rb dest=/etc/eye/zookeeper-{{ env_name }}.rb owner=root group=root mode=0644 backup=yes
  when: ansible_os_family != 'Elbrus' and "not (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04')"

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
  become: yes
  when: ansible_os_family != 'Elbrus' and "not (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04')"

- name: put systemd unit file to its destination
  template: src=zookeeper.service dest=/etc/systemd/system/zookeeper-{{ env_name }}.service owner=root group=root mode=0644
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'"
  notify: systemctl daemon-reload

- name: enable zookeeper service
  service: name=zookeeper-{{ env_name }} enabled=yes state=started
  when: "ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'"
